name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'idea-vault/package-lock.json'

      - name: Install dependencies
        working-directory: ./idea-vault
        run: npm ci --legacy-peer-deps

      - name: Lint
        working-directory: ./idea-vault
        run: npm run lint

      - name: Type check
        working-directory: ./idea-vault
        run: npx tsc --noEmit

      - name: Build
        working-directory: ./idea-vault
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      # Tests will be added in future iterations
      # - name: Test
      #   working-directory: ./idea-vault
      #   run: npm run test